apiVersion: v1
kind: Namespace
metadata:
  name: test-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: test-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: test-worker
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-worker
  namespace: test-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-worker
  template:
    metadata:
      labels:
        app: test-worker
    spec:
      containers:
        - name: worker
          image: test-worker:latest
          imagePullPolicy: Always
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
          command:
            - celery
            - -A
            - app
            - worker
            - -Q
            - test
            - -c
            - "1"
            - -l
            - debug
            - --without-gossip
            - --disable-prefetch
            - --max-tasks-per-child=1
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 500Mi
